#!/bin/bash

# Specify the MongoDB database and collection names
database="my_db"
collection="school"

# Execute the MongoDB find command
mongo "$database" --quiet --eval "db.$collection.find({ name: /^Holberton/ })"

